### ISSUE TITLE
JavaScript snippet generator emits improper HTML

### ISSUE THREAD

**Issue by DamianEdwards** [Microsoft/ApplicationInsights-aspnet5#101]
https://github.com/Microsoft/ApplicationInsights-aspnet5/blob/master/src/Microsoft.ApplicationInsights.AspNet/ApplicationInsightsJavaScript.cs#L22

Two things wrong with the script tag here:
- Should use `type="text/javascript"` instead of `language='javascript'`
- Shouldn't have spaces on either side of the `=` sign

The first is causing warnings to be logged in Internet Explorer console.

**Comment by SergeyKanzhelev** [comment]
Fixed
