### ISSUE TITLE
AppInsights JS file is served from server with no GZIP compression

### ISSUE THREAD

**Issue by DamianEdwards** [Microsoft/ApplicationInsights-aspnet5#102]
![image](https://cloud.githubusercontent.com/assets/249088/8935696/e8a15340-3502-11e5-95ad-687a637dd823.png)

Big savings to be had here if GZIP is enabled on the server for resource `https://c.microsoft.com/ms.js`. Having nearly 50 KB of JS for telemetry is a little obscene.

**Comment by SergeyKanzhelev** [comment]
@MaxShehovtsov can you look into it please?

**Comment by MaxShehovtsov** [comment]
@DamianEdwards why do you think 50 KB is worth improving? We though about it and the real performance gain seemed to be intangible (lets assume we reduce it to 5 or even 1 KB). I'd love to be convinced in the opposite - please help me with that!

**Comment by DamianEdwards** [comment]
@MaxShehovtsov because turning on GZIP is completely painless and will save you 30 KB. I just added AppInsights to a page and it increased the overall download size by nearly 20%. That's totally unexpected, especially when Google Analytics on the same page takes just 11 KB (it's compressed).

**Comment by MaxShehovtsov** [comment]
@DamianEdwards I see your point. Do you know roughly what's the download *speed* gain?

**Comment by DamianEdwards** [comment]
@MaxShehovtsov that's totally dependent on the device and connection. This isn't about speed, it's about best practices for front-end web optimization. You should GZIP compressible files, period. Even more so because you're an external resource that will be compared to competitive products.

But as you asked:

![image](https://cloud.githubusercontent.com/assets/249088/8936343/7c71451e-3506-11e5-9fb3-1bb216a324c3.png)

**Comment by MaxShehovtsov** [comment]
@DamianEdwards That makes sense, thanks!

**Comment by SergeyKanzhelev** [comment]
Corresponding issue on JS SDK was closed https://github.com/Microsoft/ApplicationInsights-JS/issues/42. It seems to be compressed now:

![image](https://cloud.githubusercontent.com/assets/9950081/10837453/cf6eefdc-7e76-11e5-9c85-e98e43affc01.png)
