### ISSUE TITLE
Custom Events not getting sent

### ISSUE THREAD

**Issue by avodovnik** [Microsoft/ApplicationInsights-aspnet5#115]
I'm trying to test out sending custom events through an MVC 6 application, but am not seeing any of them coming up. I **am** seeing other events (response times, page loads, etc.). 

The sample code is available here: https://github.com/avodovnik/MonitoringApplications. You can find the `TrackEvent` being called in `HomeController`'s `Contact` and `GenerateEvents`.

I tried sending events with a properties dictionary, then reverted to simple events, still to no awail. Am not getting any info in the output view inside Visual Studio except for requests. 

Am I missing something?

**Comment by SergeyKanzhelev** [comment]
Dup for this: https://github.com/Microsoft/ApplicationInsights-aspnet5/issues/78 Workaround is to take TelemetryClient from DI. Thanks for reporting. We are still not clear how to fix it. Feel free to make suggestions that would work for you the best.

**Comment by avodovnik** [comment]
Hey, that makes a lot of sense. But it would make a lot of sense if there was an output somewhere in the debug window that the event is not sent due to no Key being set. Maybe even an exception thrown, although not sure about that. Also, to prevent this, maybe a good approach would be to have an ITelemetryClientProvider and an ITelemetryClient with an "internal" implementation registered to the DI container (at least for ASP.NET 5).

**Comment by gardnerjr** [comment]
both this one and #78 are closed with pointers to eachother.  was there a fix to one or the other?  or is this getting fixed by adding the (not configured) output in debug mode?

**Comment by SergeyKanzhelev** [comment]
#78 is open.

**Comment by gardnerjr** [comment]
yeah, i got confused because the bottom comment on #78 was about this one getting closed.  so at the bottom of the comments i saw the red "closed" and missed that it was a linked item that was closed. :|
