### ISSUE TITLE
Rename ASP.NET v5 and vNext to ASP.NET 5 to make branding consistent

### ISSUE THREAD

**Issue by SergKanz** [Microsoft/ApplicationInsights-aspnet5#63]

**Comment by olegsych** [comment]
Do we need to create issues for pull requests that were already submitted? It feels confusing because the discussion is already happening on the pull request.

**Comment by SergKanz** [comment]
It is for readme files and wiki pages. I'm thinking to rename repository as well - not sure about this last one though

**Comment by Eilon** [comment]
BTW if you rename the GitHub repo then GitHub will automatically redirect all old URLs to the new URL, so it's quite safe. We've done tons of repo renames and haven't had any issues.

**Comment by olegsych** [comment]
That's good to know. Thanks @Eilon

**Comment by SergKanz** [comment]
Fixed in [PR 71](https://github.com/Microsoft/ApplicationInsights-aspnet5/pull/71) and wiki was updated

**Comment by Eilon** [comment]
Thanks!
