### ISSUE TITLE
Reference ASP.NET "Abstractions" / "Interfaces" packages instead of concrete implementations

### ISSUE THREAD

**Issue by Eilon** [Microsoft/ApplicationInsights-aspnet5#69]
Many of the packages in ASP.NET 5 and DNX now have "Abstractions" packages (as of beta5; in beta4 these were generally "Interfaces" packages) that contain just the raw interfaces, without specific implementations. As a general rule, library packages (such as Application Insights) should reference the abstractions and not concrete implementations.

E.g. the references here: https://github.com/Microsoft/ApplicationInsights-aspnet5/blob/master/src/Microsoft.ApplicationInsights.AspNet/project.json#L13-L17

You should be able to change the reference to `Microsoft.Framework.Logging` to instead be `Microsoft.Framework.Logging.Abstractions` (in beta5; or use `Microsoft.Framework.Logging.Interfaces` in beta4).

**Comment by SergKanz** [comment]
Fixed in [PR 72](https://github.com/Microsoft/ApplicationInsights-aspnet5/pull/72)
